### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [whh8b/slackman#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from another library before this would be possible?

**Comment by hawkinsw** [comment]
Thank you so much for alerting me to this. It was really simple to remove the dependency and replace it with the serde library. Even though this is just a personal project, getting it corrected is really important. Thanks again for alerting me to it.

**Comment by hawkinsw** [comment]
Fixed in b4bf3562c33915c841a109e7f425d2ca0d25dbf2.
